### ISSUE TITLE
Thanks for the well commented code

### ISSUE THREAD

**Issue by ret394** [francoiswnel/Hack-Assembler#2]
I know this is pretty common for you.

I'll add more praise when I look at it later. And cry with the sheer happiness of this surprising discovery.

And maybe actually run this beautiful code. Whenever I can.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by francoiswnel** [comment]
Thanks! This code is actually pretty old by now and not what I'd call beautiful, but I did try to document it with comments as well as I could! Maybe one day I'll revisit it and refactor it.
